### ISSUE TITLE
Show/Hide crosshair only hides

### ISSUE THREAD

**Issue by K3end0** [lacymorrow/crossover#216] opened 2022-10-20 14:42 UTC
The keybind name suggests pressing ctrl+shift+alt+h will toggle hidden and revealed states, but it only hides and does not unhide the crosshair.

**Comment by shittymacuser** [comment] 2022-10-23 06:25
you gotta do ctrl+shift+alt+x itll toggle it on again 

use your brain next time bruh

**Comment by K3end0** [comment] 2022-10-23 09:45
> you gotta do ctrl+shift+alt+x itll toggle it on again
> 
> use your brain next time bruh

Yes I know, because that's what I currently do. That does not change the fact the hide/show feature is currently half broken.

It's also not a perfect get-around to the broken feature however, as sometimes it opens with the menu screen.

**Comment by lacymorrow** [comment] 2022-10-31 21:43
No need to use insults, this issue has been reported elsewhere in Arch Linux. 
What OS are you using @K3end0?

If you have the time, I'm wondering if there is another program interfering with that keybind, could you try changing the keybind and seeing if you can hide/show CrossOver?

**Comment by lacymorrow** [comment] 2022-10-31 22:46
Thank you for testing that for me, I'll have to think about this. Do you know how to run crossover as an administrator? That may be worth testing.

I'm running windows 10 as well, so it's hard to figure out what the issue is

**Comment by K3end0** [comment] 2022-10-31 22:55
Closed crossover and then ran it as administrator, sadly no change.

**Comment by lacymorrow** [comment] 2022-10-31 23:03
Dang.

**Comment by Berzasperd** [comment] 2022-12-31 04:08
I too experienced this issue on Windows 10.  While it is possible to re-show the cursor using the Lock Crosshair in Place hotkey (twice, once to show it / unlock, second to re-lock it), this causes some windows to lose focus, which is a little quirky depending on what you are running at the time.  In my case, Fallout 4 will usually open the main menu whenever the window loses focus, thus requiring me to additionally press Esc to get back to normal.

Based on the reading of the method / code at:
https://github.com/lacymorrow/crossover/blob/1d2a943ac7509195600cd5bbf6c99475105bacb1/src/main/windows.js#L388
I suspect what is happening that the program is not able to tell when the crosshair is hidden, and thus cannot tell what to do when the hotkey calls for showing it again.  I have an idea that would require some testing but at the time of writing this, I can't for the life of me figure out how to get an Electron IDE running to recompile the code into a new .exe file with the changes I think might help.  In lieu of me making a pull request, I'm going to post the code changes in this issue thread for now.  It'll help me get back to it easier in the future when I figure more things out.  If it turns out this would work, feel free to incorporate it into the program in the next update.

const showHideWindow = () => {

	// NOT check on windows.hidden boolean assume the crosshair is already shown at start, thus !windows.hidden == TRUE
	if ( !windows.hidden ) {
// hide the crosshair is condition is met
		hideWindow()

	} else {
// always attempt to show the crosshair when the hotkey is pressed when IF condition fails
		showWindow()

	}
// this toggles windows.hidden boolean to opposite value each time the hotkey is pressed if I understand correctly
	windows.hidden = !windows.hidden
	
These above changes would only work if windows.hidden initializes as FALSE at the program start, otherwise the IF will never succeed.  Considering that I haven't looked at all the source code regarding this feature, it might be too risky to make that assumption, since you won't be able to ever hide the crosshair at that point.  Either way, maybe this will inspire someone more clever than I to tackle this issue, as it would be quite nice to see it resolved.

**Comment by lacymorrow** [comment] 2023-01-19 06:34
> I suspect what is happening that the program is not able to tell when the crosshair is hidden

This is correct. Thank you for reporting, PRs welcome!

**Comment by lacymorrow** [comment] 2023-06-03 06:59
This should be fixed in an upcoming release and in the dev branch

**Comment by lacymorrow** [comment] 2023-06-03 07:00
@K3end0 it could also be a conflict with keybinds from other software you have running.

**Comment by lacymorrow** [comment] 2023-06-03 07:11
Regardless, fix inbound

**Comment by lacymorrow** [comment] 2023-06-05 04:33
Fixed in https://github.com/lacymorrow/crossover/pull/266

**Closed by lacymorrow** 2023-06-05 04:33 UTC
Labels: Done
