### ISSUE TITLE
[BUG] The crosshair wont hide when aiming with the right mouse button.

### ISSUE THREAD

**Issue by GenericGeorge** [lacymorrow/crossover#304] opened 2023-11-01 17:57 UTC
**Describe the issue**
I can't get the crosshair to hide when enabled with any mouse button.

Need help with getting the crosshair to hide when I'm aimed in. My last installation was downloaded from github, used it for months with this feature working, then I got a notification that it will autoupdate, something broke and it ended up just uninstalling itself. I then decided to download the program from the windows store instead and came across this bug. I've seen the bug before on a couple versions or so before but it fixed itself.

**To Reproduce**
What I do is enable the hide crosshair on ADS setting, I set it to right mouse-button. Then try hiding the crosshair, it does not work for me. I think I played around with the change crosshair size when ADSing but I changed that back to never and the scroll bar near to where it was originally.

**Screenshots**
I don't think a screenshot of something not happening is possible. I'm sorry

**Versions (please complete the following information):**
 - OS: Windows 11 Pro 64bit
 - CrossOver Version: 3.2.0
 From the Windows Store.

**Comment by GenericGeorge** [comment] 2023-11-01 18:49
Reinstalled after removing everything lacy morrow / crossover that the windows explorer search feature could find (ini file and other stuffs. To make sure it was a fresh install, this time went for the latest github release and it now works. Maybe it's just the windows app version?

**Comment by lacymorrow** [comment] 2023-11-01 20:19
Heads up, I fixed this issue in 3.2.1, and some more bugs yesterday and today. Try the current and let me know if it fixes the issue: https://github.com/lacymorrow/crossover/releases/latest

**Comment by lacymorrow** [comment] 2023-11-01 20:21
By the way, thank you for your issue! I'm the sole developer and don't have the ability to do full tests across all OS'. Your reports help make this app better 💯

**Comment by nomis51** [comment] 2023-11-01 22:43
( #301 ) I can confirm the issue is fixed as of 3.2.1+

**Comment by lacymorrow** [comment] 2023-11-02 04:22
Thank you so much for your report and help!

**Closed by lacymorrow** 2023-11-02 04:22 UTC
Labels: bug
