### ISSUE TITLE
Modal window

### ISSUE THREAD

**Issue by anshpreet-s** [lacymorrow/crossover#21] opened 2020-05-17 17:56 UTC
I am not able to select any crosshair design nor am i able to close the modal window please help
It freezes everything

**Comment by lacymorrow** [comment] 2020-05-17 20:13
Hi @anshpreet-s, I'm not sure what could be going on. What operating system are you using? The escape key should close the chooser window if the program is focused.

If you like we can live chat via discord or slack

**Comment by anshpreet-s** [comment] 2020-05-18 00:36
I am using Windows 10 and no the escape key is not working either

**Comment by anshpreet-s** [comment] 2020-05-18 02:45
yeah so i was poking around the different versions of crossover and i find that v0.3.1 works for me but 0.3.2 does  not work for me it freezes up every time

**Comment by lacymorrow** [comment] 2020-05-18 06:42
Hi @anshpreet-s, thanks for poking around. There was an issue with version 0.3.1 that makes CrossOver capture the escape key so that other applications cannot use it.

I'm fixing this and should have a new version tomorrow.
Thanks so much for reporting.

**Comment by lacymorrow** [comment] 2020-05-18 07:05
@anshpreet-s If you could attach a screenshot, I would very much appreciate it

**Comment by atlasix0425** [comment] 2020-05-18 09:46
I'm having the same problem. Can Not choose custom crosshair on 0.3.2, but 0.3.1 works perfectly. When I tap "Choose Crosshair" on 0.3.2, the popup window just froze, I'm able to close the frozen window by "Alt+F4", but If I click "Choose Crosshair" again. A warning window would pops up. I want give you more information about the warning window, but after I uninstall 0.3.1, than install 0.3.2 just to see the old problem.........    The problem just gone, 0.3.2 works well after I install&uninstall 0.3.1............     Now both version works well.........

-

**Comment by PaulCombal** [comment] 2020-05-18 17:35
Same issue with Win 10, waiting for a fix. There's not much to screenshot except for the fact that the window shows correctly but clicking a crosshair style doesn't do anything.

**Comment by lacymorrow** [comment] 2020-05-18 19:54
@PaulCombal @atlasix0425 Thanks for the information, super helpful.

**Comment by lacymorrow** [comment] 2020-05-18 21:40
Who can test for me? Since I can't reproduce the issue I need someone who is having problems test my fixes.

I'm uploading a new version here, can someone test?
https://github.com/lacymorrow/crossover/releases

cc @PaulCombal @anshpreet-s @atlasix0425 @mogulftw

**Comment by PaulCombal** [comment] 2020-05-18 22:57
I probably can do this tomorrow if nobody does it before. By the way is there a way to show the console so that in case it's not it I can provide the error details?

**Comment by lacymorrow** [comment] 2020-05-18 23:02
@PaulCombal You're the man, thanks for the offer. 

Unfortunately, this version didn't fix the issue.I found a machine that I can reproduce the issue on so another fix is coming soon.

**Comment by lacymorrow** [comment] 2020-05-19 02:20
The latest version should this issue and a few more: https://github.com/lacymorrow/crossover/releases/latest

Thank you all for your reports! I wouldn't be able to maintain the app without feedback like this.

**Comment by PaulCombal** [comment] 2020-05-19 15:50
Haha no worries I know what it's like :) Anyway thank YOU for making this tool <3

Feel free to close the issue if there's nothing more we can do btw

**Closed** 2020-05-19 16:20 UTC
