### ISSUE TITLE
有没有全屏下使用crossover的教程

### ISSUE THREAD

**Issue by cznb666** [lacymorrow/crossover#142] opened 2022-03-25 05:22 UTC
ahk导入脚本不会，请问有没有教程，谢谢了

**Comment by lacymorrow** [comment] 2022-03-25 07:23
>Is there a tutorial for using crossover in full screen?
>ahk import script will not, is there any tutorial, thank you

Unfortunately this is a problem with "electron" not crossover.
I recommend windowed fullscreen mode

**Comment by lacymorrow** [comment] 2022-03-25 07:24
Duplicate of #106

**Closed** 2022-03-31 22:37 UTC
