### ISSUE TITLE
Getting this whenever I launch crossover. 

### ISSUE THREAD

**Issue by Meezy98** [lacymorrow/crossover#183] opened 2022-05-11 21:54 UTC
---
	
	TypeError: Cannot read property 'setBadge' of undefined:
	TypeError: Cannot read property 'setBadge' of undefined
    at Object.setBadge (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\src\main\dock.js:5:35)
    at NsisUpdater.onUpdateDownloaded (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\src\main\auto-update.js:51:7)
    at NsisUpdater.emit (events.js:315:20)
    at NsisUpdater.dispatchUpdateDownloaded (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:581:10)
    at Object.done (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\BaseUpdater.js:42:14)
    at done (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:719:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NsisUpdater.executeDownload (C:\Users\Kymon\AppData\Local\Programs\crossover\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:730:14)

	---

	CrossOver 3.0.1
Electron 11.5.0
win32 10.0.19043
Locale: en-US

**Comment by lacymorrow** [comment] 2022-05-11 22:23
Please update to the latest version, this has been fixed.

Duplicate of #153

**Closed by lacymorrow** 2022-05-11 22:23 UTC
