### ISSUE TITLE
[Arch: AMD] Toggling crosshair causes lag spike & resets ReLive's Instant Replay.

### ISSUE THREAD

**Issue by xzuyn** [lacymorrow/crossover#221] opened 2022-11-27 04:48 UTC
When you hide/unhide the crosshair the game will lock up for a split second (duration of the hide/unhide animation maybe?), and AMD's instant replay recording will get reset. 

Disabling Freesync, and trying with hardware acceleration on and off doesn't change anything. Disabling instant replay still has lag.

Attached video recorded with OBS. You can't tell from the video really that there is a spike cause I guess its spiking to above 60fps, but I can feel and see it on my monitor, and you can see the dip with fraps. At first I only click slowly, then I click rapidly to show how bad it can get. You can also see the indicator in the top left is resetting every time I hide/unhide the crosshair. 

My guess is it's to due with how crossover hides/unhides them window, or maybe it's caused by the fading of the crosshair instead of it being and instant on/off (which I would prefer even if it didn't fix this).

I don't know how this program works, but maybe make the crosshair turn transparent or something so nothing about crossover's window really changes so anything that looks for the focused/main window (instant replay or freesync) doesn't see crossover as the new focused/main window, then back to the game as the focused/main window. If that's what it does already, idk. 

https://user-images.githubusercontent.com/16216325/204119596-d8b160ac-a696-4d3f-8753-b1cfce961b2d.mp4

**Comment by lacymorrow** [comment] 2022-11-28 05:24
I appreciate the digging you've done. It could be caused by the fade, the iohook native library I'm using on Arch, or possibly a conflicting keybind. Hopefully the former, I'll add an option to disable the fade.

**Comment by lacymorrow** [comment] 2022-11-28 05:25
#222

**Comment by xzuyn** [comment] 2022-11-28 05:32
Also is arch short for architecture or is it Arch Linux? Cause I noticed you changed my previous issue to that so I labeled this one that way as well assuming that it was architecture (like nvidia gpu or amd gpu), but I am running Windows 10 Pro 22H2 (19045.2251) with an RX 480 8GB if it's meant to mean Linux.

**Comment by lacymorrow** [comment] 2022-11-28 05:36
Also, yep, arch is for architecture (intel vs amd vs m1/2), I see where the confusion came from.

**Comment by xzuyn** [comment] 2022-11-28 05:37
Alright, just wanted to make sure I wasn't providing misleading/incorrect information.

**Comment by lacymorrow** [comment] 2023-06-03 08:24
This should be fixed in the pre-release version posted soon.

**Closed** 2023-06-05 05:11 UTC
