### ISSUE TITLE
importatn issue

### ISSUE THREAD

**Issue by IGOROLOxd** [lacymorrow/crossover#148] opened 2022-04-01 16:33 UTC
```
Error: EPERM: operation not permitted, rename 'C:\Users\UsuarioPC\AppData\Roaming\CrossOver\preferences.json.3751857556' -> 'C:\Users\UsuarioPC\AppData\Roaming\CrossOver\preferences.json'
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.22000
Locale: es

**Comment by lacymorrow** [comment] 2022-04-01 21:03
Current suggestion is to downgrade to v2.5.0: https://github.com/lacymorrow/crossover/releases/tag/v2.5.0

Check back next week for a fixed version with new features!

Duplicate of #146

**Closed by lacymorrow** 2022-04-01 21:03 UTC
